/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example.app;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;

import static org.junit.jupiter.api.Assertions.*;

@SpringBootTest
class TestApp {

    @Test
    void contextLoads() {
    }
}
